/*
 * Yournal API
 *
 * Documentation and definition of the Yournal API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 0.1.0
 * Contact: hi@yournal.tk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCurrentUser - Get current user
func GetCurrentUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// OAuth2 - User Authentification endpoint
func OAuth2(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateCurrentUser - Update current user
func UpdateCurrentUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
