/*
 * Yournal API
 *
 * Documentation and definition of the Yournal API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 0.1.0
 * Contact: hi@yournal.tk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

type oAuthType string

// List of oAuthType
const (
	APPLE     string = "Apple"
	GOOGLE    string = "Google"
	MICROSOFT string = "Microsoft"
)
