/*
 * Yournal API
 *
 * Documentation and definition of the Yournal API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 0.1.0
 * Contact: hi@yournal.tk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

//UpdatePosts constructs PostUpdate
type UpdatePosts struct {
	Title string `json:"title,omitempty"`

	CoverImage string `json:"coverImage,omitempty"`

	Body string `json:"body,omitempty"`
}
