/*
 * Yournal API
 *
 * Documentation and definition of the Yournal API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 0.1.0
 * Contact: hi@yournal.tk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/maxzerbini/oauth"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	router.Use(gin.Logger())
	router.Use(gin.Recovery())
	router.GET("/", Index)
	registerAPI(router)

	return router
}

//NewRouterGroup returns a Router Group for authenticated access
func NewRouterGroup(router *gin.Engine, path string) *gin.RouterGroup {
	group := router.Group(path)
	group.Use(oauth.Authorize(secret, nil))
	{
		for _, route := range routes {
			switch route.Method {
			case http.MethodGet:
				group.GET(route.Pattern, route.HandlerFunc)
			case http.MethodPost:
				group.POST(route.Pattern, route.HandlerFunc)
			case http.MethodPut:
				group.PUT(route.Pattern, route.HandlerFunc)
			case http.MethodDelete:
				group.DELETE(route.Pattern, route.HandlerFunc)
			}
		}
	}
	return group
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"DeletePost",
		http.MethodDelete,
		"/posts/:slug",
		DeletePost,
	},

	{
		"GetPost",
		http.MethodGet,
		"/posts/:slug",
		GetPost,
	},

	{
		"GetPosts",
		http.MethodGet,
		"/posts",
		GetPosts,
	},

	{
		"UpdatePost",
		http.MethodPut,
		"/posts/:slug",
		UpdatePost,
	},

	{
		"GetCurrentUser",
		http.MethodGet,
		"/users",
		GetCurrentUser,
	},
	{
		"UpdateCurrentUser",
		http.MethodPut,
		"/users",
		UpdateCurrentUser,
	},
}
